version: "3.9"
services:
  db_dish:
    image: postgres
    container_name: db_dish
    environment:
      - POSTGRES_DB=dish_db
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db_dish/dish_db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dish
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://db_dish:5432/dish_db
      - SPRING.DATASOURCE.USERNAME=postgres
      - SPRING.DATASOURCE.PASSWORD=password
      - SPRING.DATASOURCE.DRIVER-CLASS-NAME=org.postgresql.Driver
    ports:
      - "8081:8081"
    depends_on:
      - db_dish
